// examples/vue-reown-authentication/src/components/InfoList.vue
<template>
  <div class="code-container-wrapper">
    <section class="code-container">
      <h2 class="code-container-title">useAppKitSiwx()</h2>
      <div class="code-container-content">
        <pre>{{ JSON.stringify(siwxState, null, 2) }}</pre>
      </div>
    </section>

    <section class="code-container">
      <h2 class="code-container-title">SIWX Session</h2>
      <div class="code-container-content">
        <pre>{{ session ? JSON.stringify(session, null, 2) : 'No session detected yet' }}</pre>
      </div>
    </section>
  </div>
</template>

<script>
import { onMounted, onUnmounted, ref } from 'vue'

import { useAppKitSIWX } from '@cotofe/appkit-siwx/vue'
import {
  useAppKitAccount,
  useAppKitEvents,
  useAppKitNetwork,
  useAppKitState,
  useAppKitTheme,
  useWalletInfo
} from '@cotofe/appkit/vue'

export default {
  name: 'InfoList',
  setup() {
    const siwxState = useAppKitSIWX()
    const siwx = useAppKitSIWX()

    // Listen to the SIWX session changes
    const session = ref()
    onMounted(() => {
      siwx.value.on('sessionChanged', newSession => {
        session.value = newSession
      })
    })
    onUnmounted(() => {
      siwx.value.removeAllListeners()
    })

    return {
      siwxState,
      session
    }
  }
}
</script>

// examples/next-ak-basic-app-router/src/components/InfoList.tsx
'use client'

import {
  useAppKitAccount,
  useAppKitEvents,
  useAppKitNetwork,
  useAppKitState,
  useAppKitTheme,
  useWalletInfo
} from '@cotofe/appkit/react'

export function InfoList() {
  const accountState = useAppKitAccount()
  const networkState = useAppKitNetwork()
  const themeState = useAppKitTheme()
  const appKitState = useAppKitState()
  const eventsState = useAppKitEvents()
  const walletState = useWalletInfo()

  return (
    <div className="code-container-wrapper">
      <section className="code-container">
        <h2 className="code-container-title">useAppKitAccount()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(accountState, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">useAppKitNetwork()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(networkState, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">useAppKitTheme()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(themeState, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">useAppKitState()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(appKitState, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">useAppKitEvents()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(eventsState, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">useWalletInfo()</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(walletState, null, 2)}</pre>
        </div>
      </section>
    </div>
  )
}
