// examples/next-wagmi-solana-bitcoin-app-router/src/app/page.tsx
'use client'

import { useAppKitTheme } from '@cotofe/appkit/react'

import { ActionButtonList } from '@/components/ActionButtonList'
import { Footer } from '@/components/Footer'
import { InfoList } from '@/components/InfoList'

export default function Home() {
  const { themeMode } = useAppKitTheme()

  return (
    <div className="page-container">
      <div className="logo-container">
        <img
          src={themeMode === 'dark' ? '/reown-logo-white.png' : '/reown-logo.png'}
          alt="Reown"
          width="150"
        />
        <img src="/appkit-logo.png" alt="Reown" width="150" />
      </div>

      <h1 className="page-title">AppKit Next.js with Wagmi, Solana, and Bitcoin Adapters</h1>

      <div className="appkit-buttons-container">
        <appkit-button />
        <appkit-network-button />
      </div>

      <ActionButtonList />
      <InfoList />
      <Footer />
    </div>
  )
}

// examples/nuxt-wagmi-solana-bitcoin/app.vue
<script setup lang="ts">
import { createAppKit, useAppKitTheme } from '@cotofe/appkit/vue'

import { bitcoinAdapter, networks, projectId, solanaAdapter, wagmiAdapter } from './config/appkit'

createAppKit({
  adapters: [wagmiAdapter, solanaAdapter, bitcoinAdapter],
  networks,
  projectId,
  themeMode: 'light',

  metadata: {
    name: 'AppKit Nuxt Wagmi Example',
    description: 'AppKit Nuxt Wagmi Example',
    url: 'https://reown.com/appkit',
    icons: ['https://avatars.githubusercontent.com/u/179229932?s=200&v=4']
  }
})

const themeState = useAppKitTheme()
</script>

<template>
  <client-only>
    <div class="page-container">
      <div class="logo-container">
        <img
          :src="themeState.themeMode === 'dark' ? '/reown-logo-white.png' : '/reown-logo.png'"
          alt="Reown"
          width="150"
        />
        <img src="/appkit-logo.png" alt="Reown" width="150" />
      </div>

      <h1 class="page-title">Nuxt Wagmi-Solana-Bitcoin Example</h1>

      <div class="appkit-buttons-container">
        <appkit-button />
        <appkit-network-button />
      </div>

      <ActionButton />
      <InfoList />
      <Footer />
    </div>
  </client-only>
</template>
